{{- if and .Values.aws.route53.enabled (not .Values.aws.route53.externalDNS) }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "mychart.fullname" . }}-dns-record
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  endpoints:
  - dnsName: {{ .Values.aws.route53.recordName }}.{{ .Values.aws.route53.zoneName }}
    recordTTL: {{ .Values.aws.route53.ttl }}
    recordType: A
    targets:
    - {{ "{{ .status.loadBalancer.ingress.hostname }}" }}
    providerSpecific:
    - name: alias
      value: "true"
    - name: aws/alb-target-health-evaluations
      value: zero
{{- end }} 