{{- if .Values.secrets.default.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-secret
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.default.data | nindent 2 }}
{{- end }}
---
{{- if .Values.secrets.app.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-app-secret
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.app.data | nindent 2 }}
{{- end }}
---
{{- if and .Values.aws.ssmParameterStore.enabled .Values.aws.ssmParameterStore.asEnvironmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-ssm-params
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    secrets-store.csi.k8s.io/managed: "true"
type: Opaque
data: {}
{{- end }} 